// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR1FrKooBu4Gp7nwMMepntlzckC5RBjdI',
    appId: '1:31597212976:web:54d5716fadf7ad78c844f5',
    messagingSenderId: '31597212976',
    projectId: 'sandwich-shop-bba8f',
    authDomain: 'sandwich-shop-bba8f.firebaseapp.com',
    databaseURL: 'https://sandwich-shop-bba8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandwich-shop-bba8f.firebasestorage.app',
    measurementId: 'G-M40Q0FWKMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWUxLXvCOnfTOFim-Kp_eHwdpo-aXysXE',
    appId: '1:31597212976:android:0837d95f0c975043c844f5',
    messagingSenderId: '31597212976',
    projectId: 'sandwich-shop-bba8f',
    databaseURL: 'https://sandwich-shop-bba8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandwich-shop-bba8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe9UkR8QPxQls-_Sbqj9njTT3OxlwLlDM',
    appId: '1:31597212976:ios:968dfe6957fcec79c844f5',
    messagingSenderId: '31597212976',
    projectId: 'sandwich-shop-bba8f',
    databaseURL: 'https://sandwich-shop-bba8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandwich-shop-bba8f.firebasestorage.app',
    iosBundleId: 'com.example.sandwichShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe9UkR8QPxQls-_Sbqj9njTT3OxlwLlDM',
    appId: '1:31597212976:ios:968dfe6957fcec79c844f5',
    messagingSenderId: '31597212976',
    projectId: 'sandwich-shop-bba8f',
    databaseURL: 'https://sandwich-shop-bba8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandwich-shop-bba8f.firebasestorage.app',
    iosBundleId: 'com.example.sandwichShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR1FrKooBu4Gp7nwMMepntlzckC5RBjdI',
    appId: '1:31597212976:web:172b2a51e89bbc29c844f5',
    messagingSenderId: '31597212976',
    projectId: 'sandwich-shop-bba8f',
    authDomain: 'sandwich-shop-bba8f.firebaseapp.com',
    databaseURL: 'https://sandwich-shop-bba8f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sandwich-shop-bba8f.firebasestorage.app',
    measurementId: 'G-N5R8X8LRQW',
  );

}